Log all results which are not unique
sapcc/networking-nsx-t pull request #123
Opened 2023-08-17 14:56 UTC by sven-rosenzweig

The result popped from the list does not appear in the warning log.

2023-10-03 09:29 UTC, notandy commented
Hrm, isn't this change logging everything as "ambiguous?

2023-10-03 13:47 UTC, notandy requested changes
Hrm, isn't this change logging everything as "ambiguous?

2023-11-01 12:50 UTC, notandy commented
> @notandy Also increased the log level to error in order to make them visible to us. In the past we had issues with duplicate entries. Do you agree on that?

I am fine with the log level increase, the PR doesn't not really changes anything else, right?

2024-01-30 15:02 UTC, joroaf approved these changes

2024-01-30 15:48 UTC, notandy approved these changes

2024-01-30 15:48 UTC, merged